const CORRECT_PASSWORD='love';const slides=[...document.querySelectorAll('.slide')];const dots=document.querySelector('#dots');const song=document.querySelector('#song');const sound=document.querySelector('#sound');let current=0;
slides.forEach((_,index)=>{const dot=document.createElement('button');dot.className=`dot${index===0?' active':''}`;dot.setAttribute('aria-label',`Go to message ${index+1}`);dot.addEventListener('click',()=>go(index));dots.appendChild(dot)});
function go(index){current=(index+slides.length)%slides.length;slides.forEach((slide,i)=>slide.classList.toggle('active',i===current));[...dots.children].forEach((dot,i)=>dot.classList.toggle('active',i===current))}
document.querySelectorAll('.next').forEach(button=>button.addEventListener('click',()=>go(current+1)));document.querySelector('#previous').addEventListener('click',()=>go(current-1));document.querySelector('#restart').addEventListener('click',()=>go(0));
sound.addEventListener('click',()=>{if(song.paused){song.play().then(()=>sound.textContent='Ⅱ').catch(()=>sound.textContent='♫')}else{song.pause();sound.textContent='♫'}});
document.querySelector('#forgive').addEventListener('click',()=>{document.querySelector('#response').textContent='Thank you for giving my heart a little hope. I will cherish it. ♥'});document.querySelector('#wait').addEventListener('click',()=>{document.querySelector('#response').textContent='I understand. Take all the time you need—I will respect your heart.'});
const symbols=['♥','✦','♡','☁'];setInterval(()=>{const item=document.createElement('span');item.className='float';item.textContent=symbols[Math.floor(Math.random()*symbols.length)];item.style.left=`${Math.random()*96}%`;item.style.animationDuration=`${6+Math.random()*4}s`;document.querySelector('#floating').appendChild(item);setTimeout(()=>item.remove(),10500)},800);
document.querySelector('#unlock-form').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#password');if(input.value===CORRECT_PASSWORD){document.querySelector('#lock-screen').classList.add('unlocked');document.querySelector('#app').classList.add('unlocked');document.querySelector('#app').setAttribute('aria-hidden','false');song.play().then(()=>sound.textContent='Ⅱ').catch(()=>{});}else{document.querySelector('#password-help').textContent='That password is not quite right—try again.';input.select()}});
const letterModal=document.querySelector('#letter-modal');document.querySelector('#open-letter').addEventListener('click',()=>{letterModal.classList.add('open');letterModal.setAttribute('aria-hidden','false')});function closeLetter(){letterModal.classList.remove('open');letterModal.setAttribute('aria-hidden','true')}document.querySelector('#close-letter').addEventListener('click',closeLetter);letterModal.addEventListener('click',event=>{if(event.target===letterModal)closeLetter()});
